workspace:
  base: /build
  path: src/github.com/wonderkind/python-connector
pipeline:
  test:
    image: 'python:3.6-stretch'
    commands:
      - 'pip install -r requirements.txt'
      - 'pip install .'
      - 'pip install pytest'
      - 'pytest'
      - 'python setup.py check'
      - 'python setup.py bdist_wheel --universal'
      - 'cat VERSION > .tags'
    when:
      event:
        - push
  publish:
    image: plugins/gcr
    registry: eu.gcr.io
    repo: eu.gcr.io/wonderkind-data/assaf-python-connector
    debug: true
    secrets:
      - google_credentials
  trigger:
    image: plugins/downstream
    settings:
      server: http://ci.k8s1.wonderkind.cloud
      token:
        from_secret: drone_token
      fork: true
      repositories:
        - octocat/Hello-World
        - octocat/Spoon-Knife
