workspace:
  base: /build
  path: src/github.com/wonderkind/python-connector
pipeline:
  test:
    image: 'python:3.6-stretch'
    commands:
      - 'pip install -r requirements.txt'
      - 'pip install .'
      - 'pip install pytest'
      - 'pytest'
      - 'python setup.py check'
      - 'python setup.py bdist_wheel --universal'
      - 'cat VERSION > .tags'
    when:
      event:
        - push
  publish:
    image: plugins/gcr
    registry: eu.gcr.io
    repo: eu.gcr.io/wonderkind-data/assaf-python-connector
    debug: true
    secrets:
      - google_credentials
  trigger:
    when:
      branch: master
    image: plugins/downstream
    server: http://drone-drone
    # this is bad but not that bad since our drone server is behind firewalls and you can't do too much with the token except for triggering builds
    token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0ZXh0IjoicmFhbTg2IiwidHlwZSI6InVzZXIifQ.spnZ2R9ile93iJIotSjNFe_BHvOzTQDl8jXdB8d1Gx8
    fork: true
    repositories:
      - wonderkind/wonderkind-data-docker-base