workspace:
  base: /build
  path: src/github.com/wonderkind/python-connector
pipeline:
  test:
    image: 'python:3.6-stretch'
    commands:
      - 'pip install -r requirements.txt'
      - 'pip install .'
      - 'pytest'
      - 'python setup.py check'
      - 'python setup.py bdist_wheel --universal'
    when:
      event:
        - push
  publish:
    commands: 'TAG=$(cat VERSION)'
    image: plugins/gcr
    registry: eu.gcr.io
    repo: eu.gcr.io/wonderkind-data/assaf-python-connector
    tag: '${TAG}'
    debug: true
    secrets:
      - google_credentials
